JukeBox/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'jb'
urlpatterns = [
    path('', views.index, name='index'),
    path('listen', views.index),
    path('listen/<slug:room_slug>', views.listen, name='listen'),
    path('manage', views.index),
    path('manage/<slug:room_id>', views.manage, name='manage'),
    path('api/<slug:room_slug>', views.CurrentStateView.as_view()),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contact', views.contact, name='contact')
    ]

JukeBox/templates/JukeBox/admin.html
{% extends 'Jukebox/base.html' %}
{% block body %}

<!-- Welcome message -->
<div class="container">
    {% if error %}
    {% autoescape off %}
    <div class="row mt-4">
        <div class="col">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{error}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
    </div>
    {% endautoescape %}
    {% endif %}
    <div class="row">
        <div class="col">
            <h1>Welcome in your control room!</h1>
            <h3>This site is divided into two sections:</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">On the left you can add, play and delete YouTube videos from the list.</li>
                <li class="list-group-item">On the right you can control the player.</li>
                <li class="list-group-item">In order to listen to the jukebox you have to open listener's room.</li>

            </ul>
        </div>
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">Links</div>
                <div class="card-body">
                    <h4>Control room link:</h4>
                    <input class="form-control form-control-lg mb-4" type="text" value="https://zyv1k.eu.pythonanywhere.com{% url 'jb:manage' room.pk %}">
                    <h4>Link for listeners:</h4>
                    <input class="form-control form-control-lg " type="text" value="https://zyv1k.eu.pythonanywhere.com{% url 'jb:listen' room.slug %}">

                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <!-- Add / delete / play videos -->
        <div class="col">
            <form method="post">
                {% csrf_token %}
            <h3>Add videos:</h3>
            <input type="text" class="form-control form-control-lg" placeholder="Video's name (only you can see it)" name="video_name" maxlength="25" required>
            <input type="text" class="form-control form-control-lg" placeholder="YouTube Video ID" name="video_url" maxlength="11" minlength="11" required>
            <button class="btn btn-lg btn-danger btn-block" type="submit" name="add_video_button" value="True"><span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Add video</button>
            </form>
            <h3 class="mt-4 mb-4">Your videos:</h3>
            <form method="post">
                {% csrf_token %}
            <ul class="list-group list-group-flush mb-4">
                {% if room_videos %}
            {% for video in room_videos %}
              <li class="list-group-item">
                  <div class="row">
                  <div class="col-9">
                      <button type="submit" name="delete" class="btn btn-danger" value="{{video.pk}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                      <span style="overflow:hidden;"> {{video.name}}</span>
                  </div>
                  <div class="col-3 d-flex justify-content-center">
                      <button type="submit" name="video" class="btn btn-danger" value="{{video.pk}}"><span class="glyphicon glyphicon-play" aria-hidden="true"></span></button>
                  </div>
                  </div>
              </li>
            {% endfor %}
            </ul>
                {% else %}
                <h4 class="mb-3">You don't have any videos yet.</h4><br>
                <h4>If you don't know what Video ID is check <a target="_blank" href="https://gist.github.com/jakebellacera/d81bbf12b99448188f183141e6696817">this</a> guide.</h4><br>
                <h4>Alternatively you can use those two: dQw4w9WgXcQ, djV11Xbc914.</h4>

                {% endif %}
            </form>
        </div>
        <!-- controls -->
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <h3>Controls:</h3><br>
                {% if state.paused %}
                <h3 class="d-flex justify-content-center text-danger">Currently: paused - {{state.video.name}}</h3>
                {% else %}
                <h3 class="d-flex justify-content-center text-danger">Currently: playing - {{state.video.name}}</h3>
                {% endif %}
                <div class="row mt-4">
                    <div class="col"></div>
                    <div class="col d-flex justify-content-center">
                        {% if state.paused %}
                        <button class="btn btn-lg btn-danger btn-block" name="status" value="play" type="submit" style="font-size:xx-large;">
                            <span class="glyphicon glyphicon-play"></span>
                        </button>
                        {% else %}
                        <button class="btn btn-lg btn-danger btn-block" name="status" value="pause" type="submit" style="font-size:xx-large;">
                            <span class="glyphicon glyphicon-pause"></span>
                        </button>
                        {% endif %}
                    </div>
                    <div class="col"></div>
                </div>
                <div class="row mt-4">
                    <div class="col">
                        <input type="time" class="form-control form-control-lg" step="1" name="time_value" min="00:00:00" value="00:00:00" required>
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-lg btn-block btn-danger" name="time" value="true">
                            <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                            <span> / </span>
                            <span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock %}

JukeBox/templates/JukeBox/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-dark navbar-expand-sm bg-danger">
        <div class="container">
            <a class="navbar-brand" href="{% url 'jb:index' %}" style="font-size:large;"><span class="glyphicon glyphicon-play" aria-hidden="true"></span><span class="glyphicon glyphicon-pause" aria-hidden="true"></span> YTjukebox</a>
            {% if not user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mr-3">
                    <a class="nav-link text-light" style="font-size:medium;" href="{% url 'jb:contact' %}">Contact me</a>
                </li>
                <li class="nav-item-active">
                    <a class="nav-link text-light" href="{% url 'jb:login' %}" style="font-size:medium">Log in</a>
                </li>
            </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
                <a class="nav-link text-light" style="font-size:medium;" href="{% url 'jb:contact' %}">Contact me</a>
            </li>
            <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown" style="font-size:medium">
                          <span class="glyphicon glyphicon-user"></span>
                          {{user.username}}
                      </a>
                      <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'jb:logout' %}" style="font-size:medium">
                                <span class="glyphicon glyphicon-off"></span> Log out
                            </a>
                      </div>
                </li>
        </ul>
        {% endif %}
        </div>
    </nav>
    <!-- body -->
{% block body %}
{% endblock %}
</body>
</html>

JukeBox/templates/JukeBox/contact.html
{% extends 'Jukebox/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-3">

        </div>
        <div class="col-6">
            {% if message %}
            <div class="alert alert-success text-center mt-5" role="alert">
              {{message}}
            </div>
            {% endif %}
             <form method="post">
            <div class="card mt-5">
                <div class="card-header">Contact</div>
                {% csrf_token %}
                <input class="form-control form-control-lg" placeholder="Email (optional)" type="email" name="email">
                <input required class="form-control form-control-lg" placeholder="Subject" type="text" name="subject">
                <textarea required placeholder="Message" class="form-control" rows="8" cols="50" name="content" style="font-size:small"></textarea>
            </div>
                 <button class="btn btn-danger btn-lg btn-block" type="submit">Send</button>
                 </form>
        </div>
        <div class="col-3">

        </div>
    </div>
</div>
{% endblock %}

JukeBox/templates/JukeBox/index.html
{% extends 'JukeBox/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block body %}
    <div class="container">
        <div class="row mt-4">
            <div class="col">
                {% if user.is_authenticated %}
                <p><h1>{{user}}, welcome to YTjukebox!</h1></p>
                {% else %}
                <p><h1>Welcome to YTjukebox!</h1></p>
                {% endif %}
                <p class="pt-3"><h3>This site allows you to create room and control YouTube players of everyone inside that room.</h3></p>
                <p><h4>You control jukebox (YouTube player) in the room - hence the name YTjukebox.</h4></p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col">
                <h3>How does it work?</h3>
                <ul class="list-group list-group-flush mt-4">
                    <li class="list-group-item"><h4>First, you need to create room using form below. (Logging-in isn't necessary, but greatly increases security of said room.)</h4></li>
                    <li class="list-group-item"><h4>Upon successful creation you will be redirected to your control room and given two links - one for yourself, and one for your listeners (aka everyone else).</h4></li>
                    <li class="list-group-item"><h4>Then you can add your videos of choice and play them to everyone who has listener site opened in their browser.</h4></li>
                    <li class="list-group-item"><h4>You can play, pause, change the video, and skip to specific part of it.</h4></li>
                </ul>
            </div>
            {% if user.is_authenticated %}
            <div class="col">
                <h3>Claim existing room:</h3>
                <form method="post">
                    {% csrf_token %}
                    <input required name="claim_room_id" type="text" class="form-control form-control-lg" placeholder="Room's ID">
                    <button name="claim_room" type="submit" class="btn btn-lg btn-danger btn-block" value="true">Claim room</button>
                </form>
                    <h3 class="mt-4">Your rooms:</h3>
                    <div class="list-group">
                        {% if user_rooms %}
                        {% for room in user_rooms %}
                        <a class="list-group-item list-group-item-action" href="{% url 'jb:manage' room.pk %}">{{room.name}}</a>
                        {% endfor %}
                        {% else %}
                        <h4>You don't have any rooms - create one.</h4>
                        {% endif %}
                    </div>
            </div>
            {% endif %}
        </div>
        <!-- CREATE ROOM FORM -->
        <div class="row pt-5 pb-3">
            <div class="col-3"></div>
            <div class="col-6">
                <h1></h1>
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control form-control-lg" type="text" name="name" id="Name" maxlength="50" minlength="3" placeholder="Room's name" style="font-size:large;" required>
                    {% if error %}
                    <div class="invalid-feedback" style="display:block;">
                        <h5>{{error}}</h5>
                    </div>
                      {% endif %}
                    <button class="btn btn-lg btn-block btn-danger mt-3" type="submit" style="font-size:large;" name="create_room" value="true">Create a room!</button>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
        <div class="row mt-5">
            <div class="col">
                <p><h3>Why would I use it?</h3></p>
                <p><h4>I don't know... I, personally, use it to set background music during my online tabletop RPG's sessions.</h4></p>
                <p><h5>(Are those still 'tabletop' if there is no table involved?)</h5></p>
            </div>
        </div>


    </div>
{% endblock %}

JukeBox/templates/JukeBox/listener.html
{% extends 'JukeBox/base.html' %}

{% load static %}
{% block body %}
<div class="container">
  <div class="row mt-4">
    <div class="col">
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  Some modern browsers block auto-play function. If that's the case for you, then in order to use this site you have to manually start the very first video.

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  </div>
</div>
  <div class="row">
    <div class="col d-flex justify-content-center">
      <p><h1>{{room.name}}</h1></p>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex justify-content-center">
      <p>
        <h3>
          Currently -
          <span id="Status"></span>
        </h3>
      </p>
    </div>
  </div>

  <!-- YouTube Player -->
  <div class="row mt-5">
    <div class="col d-flex justify-content-center">
      <div id="player"></div>
    </div>
  </div>

  <!-- disconnect button -->
  <div class="row mt-5">
    <div class="col"></div>
    <div class="col">
      <button id="btn_disconnect" class="btn btn-lg btn-outline-danger btn-block" style="font-size:x-large;"><span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Disconnect</button>
      <h5 id="Disconnected" class="mt-4"></h5>
    </div>
    <div class="col"></div>
  </div>
</div>

<script src="{% static 'JukeBox/script.js' %}"></script>
{% endblock %}

JukeBox/templates/JukeBox/login.html
{% extends 'Jukebox/base.html' %}

{% block body %}
<div class="container">
        {% if message %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="alert alert-danger alert-dismissible fade show mt-5" role="alert">
              <p>{{message}}</p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-3"></div>

        <div class="col-6">
            <form method="post">
            <div class="card text-center mt-5">
                <div class="card-header mb-2" style="font-size:x-large;">Log in</div>
                <div class="card-body">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col mt-3">
                                <h3>Username</h3>
                            </div>
                        </div>
                         <div class="row">
                            <div class="col">
                                <input required name="login" class="form-control form-control-lg mb-5" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h3 class="mt-4">Password</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <input required name="password" class="form-control form-control-lg mb-4" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <p class="mt-4">Don’t have an account? <a href="{% url 'jb:register' %}">Sing up</a></p>
                            </div>
                        </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-lg btn-block btn-danger" type="submit" style="font-size:large;">Log in</button>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>

        <div class="col-3"></div>
    </div>
</div>

{% endblock %}

JukeBox/templates/JukeBox/register.html
{% extends 'Jukebox/base.html' %}

{% block body %}
<div class="container">
        {% if message %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="alert alert-danger alert-dismissible fade show mt-5" role="alert">
              <p>{{message}}</p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-3"></div>

        <div class="col-6">
            <form method="post">
            <div class="card text-center mt-5">
                <div class="card-header mb-3" style="font-size:x-large;">Sign Up</div>
                <div class="card-body">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">
                                <h3>Username</h3>
                            </div>
                        </div>
                         <div class="row">
                            <div class="col">
                                <input required name="login" class="form-control form-control-lg mb-5" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h3 class="mt-4">Password</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <input required name="password" class="form-control form-control-lg mb-4" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <input required name="r_password" class="form-control form-control-lg mb-4" type="password" placeholder="Repeat password">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <p class="mt-4">Already have an account? <a href="{% url 'jb:login' %}">Log in</a></p>
                            </div>
                        </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-lg btn-block btn-danger" type="submit"><h3>Sign Up</h3></button>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>

        <div class="col-3"></div>
    </div>
</div>

{% endblock %}